name: Deploy Terraform Infra

on:
  push:
    branches: [main]
    
  pull_request:
  workflow_dispatch:

jobs:
  deploy-infra-vpc:
    name: Vpc Infra
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
       
        # Using Custom Composite action in ./composite-action/action folder
      - name: Composite Action for Deploying Terraform vpc Resources
        uses: ./composite-action/action
        with:
          aws_access_key_id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          working_directory: terraform/vpc
          environment: Production

  deploy-infra-ecs:
    name: ECS Infra
    runs-on: ubuntu-latest
    needs: deploy-infra-vpc
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Composite Action for Deploying Terraform ecs Resources
        uses: ./composite-action/action
        with:
          aws_access_key_id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          working_directory: terraform/ecs
          environment: Production    
