name: Deploy terraform infra

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  deploy-infra:
    name: ECS Infra
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
       
        # Using Custom Composite action in ./composite-action/action folder
      - name: Composite Action for Deploying Terraform Resources
        uses: ./composite-action/action
        with:
          aws_access_key_id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          working_directory: terraform/vpc
          environment: Production