name: Lifinance Docker Image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    name: Build images and push to ECR
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: node-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: 243537103529.dkr.ecr.eu-west-1.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # This step yields the following labels
      # - date+sha, e.g. 2023-01-19-da4692d,
      # - tag (if pushed).
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: 243537103529.dkr.ecr.eu-west-1.amazonaws.com/lifinance
          flavor: |
            latest=false
          tags: |
            type=raw,value={{date 'YYYY-MM-DD'}}-{{sha}}
            type=ref,event=tag
            type=edge

      - name: Build image and push to ECR
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.ref == 'refs/heads/main' }}
          platforms: ${{ (github.ref == 'refs/heads/main') && 'linux/amd64,linux/arm64' || 'linux/arm64' }}


